//Mon May 12 2025 08:33:37 GMT+0000 (Coordinated Universal Time)
//宇解自动注释
var _0x572d6c = function () {
  var _0x298a47 = true;
  return function (_0x46875e, _0xbecf1a) {
    {
      var _0x1d6054 = _0x298a47 ? function () {
        {
          if (_0xbecf1a) {
            {
              var _0x3c6ef3 = _0xbecf1a.apply(_0x46875e, arguments);
              _0xbecf1a = null;
              return _0x3c6ef3;
            }
          }
        }
      } : function () {};
      _0x298a47 = false;
      return _0x1d6054;
    }
  };
}();
var _0x5e0d4c = _0x572d6c(this, function () {
  var _0x1f57d1 = function () {};
  var _0x3221dc = function () {
    {
      var _0x40beb5;
      try {
        {
          _0x40beb5 = Function("return (function() {}.constructor(\"return this\")( ));")();
        }
      } catch (_0x4fcf51) {
        {
          _0x40beb5 = window;
        }
      }
      return _0x40beb5;
    }
  };
  var _0xfe00e8 = _0x3221dc();
  if (!_0xfe00e8.console) {
    {
      _0xfe00e8.console = function (_0x346ae0) {
        {
          var _0x241a73 = {};
          _0x241a73.log = _0x346ae0;
          _0x241a73.warn = _0x346ae0;
          _0x241a73.debug = _0x346ae0;
          _0x241a73.info = _0x346ae0;
          _0x241a73.error = _0x346ae0;
          _0x241a73.exception = _0x346ae0;
          _0x241a73.table = _0x346ae0;
          _0x241a73.trace = _0x346ae0;
          return _0x241a73;
        }
      }(_0x1f57d1);
    }
  } else {
    {
      _0xfe00e8.console.log = _0x1f57d1;
      _0xfe00e8.console.warn = _0x1f57d1;
      _0xfe00e8.console.debug = _0x1f57d1;
      _0xfe00e8.console.info = _0x1f57d1;
      _0xfe00e8.console.error = _0x1f57d1;
      _0xfe00e8.console.exception = _0x1f57d1;
      _0xfe00e8.console.table = _0x1f57d1;
      _0xfe00e8.console.trace = _0x1f57d1;
    }
  }
});
_0x5e0d4c();
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <title>功 能</title>");
document.writeln("    <style>");
document.writeln("");
document.writeln("        body {");
document.writeln("            font-family: Arial, sans-serif;");
document.writeln("            text-align: center;");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;                         ");
document.writeln("    ");
document.writeln("        }");
document.writeln("       .container {");
document.writeln("            max-width: 400px;");
document.writeln("            margin: 1px auto;");
document.writeln("            padding: 1px;");
document.writeln("            opacity: 0.6;");
document.writeln("            border-radius: 10px;");
document.writeln("            background-color: #ffffff;    ");
document.writeln("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);");
document.writeln("        }");
document.writeln("");
document.writeln("        h2 {");
document.writeln("            font-size: 25px;");
document.writeln("            margin-bottom: 5px;");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("       .status {");
document.writeln("            color: #888;");
document.writeln("            font-size: 15px;");
document.writeln("            margin-bottom: 10px;");
document.writeln("        }");
document.writeln("");
document.writeln("       .menu-item {");
document.writeln("            padding: 1px;");
document.writeln("            border-top: 1px solid #e0e0e0;");
document.writeln("            font-size: 18px;");
document.writeln("        }");
document.writeln("");
document.writeln("       .menu-item:first-child {");
document.writeln("            border-top: none;");
document.writeln("        }");
document.writeln("");
document.writeln("       .button-group {");
document.writeln("            display: flex;");
document.writeln("            justify-content: center;");
document.writeln("            align-items: center;");
document.writeln("            gap: 10px;");
document.writeln("        }");
document.writeln("");
document.writeln("       .button {");
document.writeln("            position: relative;");
document.writeln("            padding: 10px 15px;");
document.writeln("            font-size: 15px;");
document.writeln("            color: #000000;");
document.writeln("            background-color: #ffffff;");
document.writeln("            border: none;");
document.writeln("            border-radius: 5px;");
document.writeln("            cursor: pointer;");
document.writeln("            transition: background-color 0.3s;");
document.writeln("            display: flex;");
document.writeln("            align-items: center;");
document.writeln("            justify-content: space-between;");
document.writeln("            width: 100%;");
document.writeln("");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("       .switch {");
document.writeln("            position: relative;");
document.writeln("            width: 34px;");
document.writeln("            height: 20px;");
document.writeln("            margin-left: 20px;");
document.writeln("        }");
document.writeln("");
document.writeln("       .switch input {");
document.writeln("            opacity: 0;");
document.writeln("            width: 0;");
document.writeln("            height: 0;");
document.writeln("        }");
document.writeln("");
document.writeln("       .slider {");
document.writeln("            position: absolute;");
document.writeln("            cursor: pointer;");
document.writeln("            top: 0;");
document.writeln("            left: 0;");
document.writeln("            right: 0;");
document.writeln("            bottom: 0;");
document.writeln("            background-color: #ccc;");
document.writeln("            border-radius: 0;");
document.writeln("            transition:.4s;");
document.writeln("            border-radius: 10px; ");
document.writeln("            border: 0.1px solid #000000;                         ");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("       .slider:before {");
document.writeln("            position: absolute;");
document.writeln("            content: \"\";");
document.writeln("            height: 16px;");
document.writeln("            width: 16px;");
document.writeln("            left: 1.2;");
document.writeln("           top: 1.4;  ");
document.writeln("            bottom: 0;");
document.writeln("            background-color: #f8f8ff;");
document.writeln("            transition:.4s;");
document.writeln("            border-radius: 50px;            ");
document.writeln("            border: 0.1px solid #000000;  ");
document.writeln("");
document.writeln("");
document.writeln("        }");
document.writeln("");
document.writeln("");
document.writeln("        input:checked+.slider {");
document.writeln("            background-color: #33ff00;");
document.writeln("      ");
document.writeln("        }");
document.writeln("        input:checked+.slider:before {");
document.writeln("            transform: translateX(14px);");
document.writeln("        }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("       .main-button:active {");
document.writeln("            background-color: #0056b3;");
document.writeln("        }");
document.writeln("");
document.writeln("       .footer {");
document.writeln("            font-size: 18px;");
document.writeln("            color: #aaa;");
document.writeln("            margin-top: 1px;");
document.writeln("        }");
document.writeln("        ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln(".glow-button {");
document.writeln("    position: relative;");
document.writeln("    width: 240px;");
document.writeln("    height: 72px;");
document.writeln("    border: none;");
document.writeln("    border-radius: 4px;");
document.writeln("    background: transparent;");
document.writeln("    color: var(--btn-color);");
document.writeln("    font-size: 32px;");
document.writeln("    font-weight: 700;");
document.writeln("    text-align: center;");
document.writeln("    line-height: 72px;");
document.writeln("    cursor: pointer;");
document.writeln("    overflow: hidden;");
document.writeln("    box-shadow: 0 0 1px var(--btn-color);");
document.writeln(" transition: box-shadow 0.3s, background-color 0.3s, color 0.3s;   ");
document.writeln("}");
document.writeln("");
document.writeln(".glow-button:hover {");
document.writeln("    background-color: var(--btn-color);");
document.writeln("    color: #fff;");
document.writeln("    box-shadow: 0 0 5px var(--btn-color), 0 0 25px var(--btn-color), 0 0 50px var(--btn-color), 0 0 100px var(--btn-color);");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln(".glow-button:active {");
document.writeln("    background-color: var(--btn-color);");
document.writeln("    color: #fff;");
document.writeln("    box-shadow: 0 0 15px var(--btn-color), 0 0 30px var(--btn-color), 0 0 60px var(--btn-color), 0 0 120px var(--btn-color);");
document.writeln("    transform: scale(0.95);");
document.writeln("}");
document.writeln(".border-lines {");
document.writeln("    position: absolute;");
document.writeln("    top: 0;");
document.writeln("    left: 0;");
document.writeln("    width: 100%;");
document.writeln("    height: 100%;");
document.writeln("    pointer-events: none;");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln(".line {");
document.writeln("    position: absolute;");
document.writeln("    display:block ;");
document.writeln("    background: linear-gradient(90deg, transparent, var(--btn-color));");
document.writeln("}");
document.writeln(".top {");
document.writeln("    top: 0;");
document.writeln("    left: -100%;");
document.writeln("    width: 100%;");
document.writeln("    height: 2px;");
document.writeln("    animation: topAnim 1s linear infinite;");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes topAnim {");
document.writeln("    0% {");
document.writeln("        left: -100%;");
document.writeln("    }");
document.writeln("    50%,");
document.writeln("    100% {");
document.writeln("        left: 100%;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln(".right {");
document.writeln("    top: -200%;");
document.writeln("    right: 0;");
document.writeln("    width: 2px;");
document.writeln("    height: 100%;");
document.writeln("    animation: rightAnim 1s linear infinite 1s;");
document.writeln("    background: linear-gradient(200deg, transparent, var(--btn-color));");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes rightAnim {");
document.writeln("    0% {");
document.writeln("        top: -100%;");
document.writeln("    }");
document.writeln("    50%,");
document.writeln("    100% {");
document.writeln("        top: 100%;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln(".bottom {");
document.writeln("    bottom: 0;");
document.writeln("    right: -100%;");
document.writeln("    width: 70%;");
document.writeln("    height: 2px;");
document.writeln("    animation: bottomAnim 1s linear infinite 1s;");
document.writeln("    background: linear-gradient(270deg, transparent, var(--btn-color));");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes bottomAnim {");
document.writeln("    0% {");
document.writeln("        right: -100%;");
document.writeln("    }");
document.writeln("    50%,");
document.writeln("    100% {");
document.writeln("        right: 200%;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln(".left {");
document.writeln("    bottom: -100%;");
document.writeln("    left: 0;");
document.writeln("    width: 2px;");
document.writeln("    height: 100%;");
document.writeln("    animation: leftAnim 1s linear infinite 1s;");
document.writeln("    background: linear-gradient(360deg, transparent, var(--btn-color));");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes leftAnim {");
document.writeln("    0% {");
document.writeln("        bottom: -100%;");
document.writeln("    }");
document.writeln("    50%,");
document.writeln("    100% {");
document.writeln("        bottom: 10%;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("h1");
document.writeln("{");
document.writeln("    position: relative;");
document.writeln("    font-size: 5vw;");
document.writeln("    color: #252839;");
document.writeln("    line-height: 1.2em;");
document.writeln("    text-transform: uppercase;");
document.writeln("    -webkit-text-stroke: 0.3vw #383d52;");
document.writeln("}");
document.writeln("h1:before");
document.writeln("{");
document.writeln("    content: attr(data-text);");
document.writeln("    position: absolute;");
document.writeln("    top: 0;");
document.writeln("    left: 0;");
document.writeln("    width: 0;");
document.writeln("    height: 100%;");
document.writeln("    color: #000000;");
document.writeln("    overflow: hidden;");
document.writeln("    -webkit-text-stroke: 0vw #000000;");
document.writeln("    animation: animate 5s linear infinite;");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes animate");
document.writeln("{");
document.writeln("    0%,10%,100%");
document.writeln("    {");
document.writeln("        width: 0;");
document.writeln("    }");
document.writeln("    50%,100%");
document.writeln("    {");
document.writeln("        width: 100%;");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln("");
document.writeln("span1 {");
document.writeln("  font-size: 28px;");
document.writeln("  color: #000000;");
document.writeln("  animation: shadow 5s forwards;");
document.writeln("}");
document.writeln("@keyframes shadow {");
document.writeln("  from {");
document.writeln("    letter-spacing: -50px;");
document.writeln("    filter: blur(10px);");
document.writeln("");
document.writeln("  }");
document.writeln("  to {");
document.writeln("    letter-spacing: 10px;");
document.writeln("    filter: blur(2px);");
document.writeln("    ");
document.writeln("  }");
document.writeln("}");
document.writeln("");
document.writeln("    </style>");